### ISSUE TITLE
would not download dependency com.fangjia.itt

### ISSUE THREAD

**Issue by leesf** [FJShen/sparktest#1]

**Comment by FJShen** [comment]
The com.fangjia.itt package is irrelevant to the functionality of sparktest unless you need to use Intel vTune profiler to collect microarchitectural statistics of the machine (Intel ITT stands for Intel Instrumentation and Tracing Technology). For now please remove all occurrences of ITT in the source code (only in BenchmarkRunner.scala and BenchUtils.scala I believe) in order to build. Also remove the ITT dependency from pom.xml.
